name: foot_etl
version: "1.0.0"
profile: foot_etl

model-paths: ["models"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  foot_etl:
    +materialized: table

seeds:
  foot_etl:
    +column_types:
      year: integer
    worldcup_2018:
      +column_types:
        home_result: integer
        away_result: integer
    worldcup_2022:
      +column_types:
        home_result: integer
        away_result: integer
