version: 2

seeds:
  - name: matches_19302010
    description: "Historical World Cup matches from 1930 to 2010 (incl. qualifiers)"
    config:
      delimiter: ","

  - name: world_cup_matches_2014
    description: "World Cup 2014 match details"
    config:
      delimiter: ";"
      column_types:
        Year: integer
        Home Team Goals: integer
        Away Team Goals: integer
        Attendance: double
        Half-time Home Goals: integer
        Half-time Away Goals: integer
        RoundID: integer
        MatchID: integer

  - name: worldcup_2018
    description: "World Cup 2018 match results (flattened from data_2018.json)"
    config:
      delimiter: ","
      column_types:
        home_result: integer
        away_result: integer

  - name: worldcup_2022
    description: "World Cup 2022 match results (flattened from worldcup.json)"
    config:
      delimiter: ","
      column_types:
        home_result: integer
        away_result: integer
